version: '3'
services:
  influxdb:
    image: influxdb
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - "influxdb-storage:/var/lib/influxdb"
    environment:
      - INFLUXDB_DB=metricsdb
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
  telegraf:
    image: telegraf
    container_name: telegraf
    ports:
        - "8080:8080"
    links:
      - influxdb
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - "grafana-storage:/var/lib/grafana"
      - ./dashboards:/var/lib/grafana/dashboards
      - ./grafana.ini:/etc/grafana/grafana.ini 
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb

  orderbook-parser:
    image: moustakis/orderbook-parser:1.1.0
    container_name: orderbook-parser

volumes:
  grafana-storage: {}
  influxdb-storage: {}
         